name: Integration tests

on:
  # Only run when this repo changes from private to public.
  # Already public = never
  public
  # push:
  #   branches: ['main']
  # pull_request:
  #   branches: ['main']

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: 'localhost:5000'
      REGISTRY: 'localhost:5000'
    strategy:
      fail-fast: false
      matrix:
        make-target:
        - integration-test-layers
        - integration-test-misc
        - integration-test-run
        - k8s-executor-build-push integration-test-k8s

    steps:
    - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # v3
      with:
        go-version: '1.20'
    - uses: actions/checkout@b0e28b5ac45a892f91e7d036f8200cf5ed489415 # v3
    - uses: docker/setup-buildx-action@4c0219f9ac95b02789c1075625400b2acbff50b1 # v1

    - run: make install-container-diff k3s-setup
    - run: make ${{ matrix.make-target }}
